"""settings

Revision ID: 9638fcf55593
Revises: c6fb7929e968
Create Date: 2022-04-07 14:40:13.283757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9638fcf55593'
down_revision = 'c6fb7929e968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kb_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_kb', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
