"""referal_id

Revision ID: 9ac3c03f2189
Revises: ac7f8887ecca
Create Date: 2022-05-03 14:55:37.484160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac3c03f2189'
down_revision = 'ac7f8887ecca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referal_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referal_id')
    # ### end Alembic commands ###
