"""change colum type

Revision ID: ac7f8887ecca
Revises: f9c07e262311
Create Date: 2022-05-01 19:21:31.133696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7f8887ecca'
down_revision = 'f9c07e262311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
