"""user update column delete

Revision ID: c6fb7929e968
Revises: 77d37d17e066
Create Date: 2022-04-03 19:58:07.683515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fb7929e968'
down_revision = '77d37d17e066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
