name: Deploy_dev

on:
  push:
    branches: [ dev ]

jobs:

  build:
    name: Deploy_dev
    runs-on: ubuntu-latest
    env:
        PROJECT_PATH: ${{ secrets.PROJECT_PATH_DEV }}
    steps:
    - name: Pull from github and build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: PROJECT_PATH
        script: cd ${{ secrets.PROJECT_PATH_DEV }} && git stash && git pull && bash bin/deploy.sh
